name: check
on: pull_request

jobs:

  # Setup Node.js and install
  # project dependencies with pnpm.
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.1"
          cache: "pnpm"
      - name: "Installing Dependencies"
        run: pnpm install

  # Statically Typechecks the
  # `.ts` source code.
  type-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.1"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm prisma generate
      - name: 'Typechecking'
        run: pnpm tscheck

  # Check source code for lints.
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.1"
          cache: "pnpm"
      - run: pnpm install
      - name: "Check Linting"
        run: pnpm lint:check

  # Check code formatting issues.
  format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.1"
          cache: "pnpm"
      - run: pnpm install
      - name: "Check Format"
        run: pnpm fmt:check

  # Runs the tests without
  # generating the coverage report.
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.1"
          cache: "pnpm"
      - run: pnpm install
      - name: "Testing"
        run: pnpm test